#!/usr/bin/env python3
"""
import_loldrivers.py - generate windows/src/vuln_driver_hashes.h, the driver-load guard's built-in table, from the
public LOLDrivers dataset (https://www.loldrivers.io, Apache License 2.0).

The table holds the Authenticode SHA-256 digest ("Authentihash") of every sample LOLDrivers lists, and whether
LOLDrivers files the driver under "malicious" or "vulnerable driver".  The output is deterministic: the same
dataset and the same --retrieved date give the same bytes, sorted and de-duplicated, so a refresh shows up in
`git diff` as exactly the digests that were added or removed.

  tools/import_loldrivers.py                       download the dataset, rewrite windows/src/vuln_driver_hashes.h
  tools/import_loldrivers.py --input drivers.json  use a saved copy of drivers.json (no network)
  tools/import_loldrivers.py --check               compare the header in the repository with the current
                                                   dataset and report what changed; writes nothing
  tools/import_loldrivers.py --retrieved 2026-09-29   record this date instead of today's

Exit status: 0 done (or, with --check, up to date), 1 with --check when the table is out of date, 2 the dataset
could not be read.

Nothing here decides what is worth blocking.  LOLDrivers also lists drivers that legitimate software installs
(a vendor's hardware utility); the guard therefore reports a "vulnerable driver" that was already loaded at boot
only as a warning, and the operator's DriverAllowHashes list vouches for an exact build.
"""
import argparse
import datetime
import hashlib
import json
import pathlib
import re
import sys
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
URL = 'https://www.loldrivers.io/api/drivers.json'
OUTPUT = ROOT / 'windows' / 'src' / 'vuln_driver_hashes.h'
HEX64 = re.compile(r'^[0-9a-f]{64}$')

HEADER = """\
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: LOLDrivers contributors <https://github.com/magicsword-io/LOLDrivers>
//
// vuln_driver_hashes.h - Authenticode SHA-256 digests of known-vulnerable and known-malicious Windows drivers.
// GENERATED by tools/import_loldrivers.py: do not edit, regenerate.
//
// Source     : {url}  (LOLDrivers, Apache License 2.0; see LICENSES/Apache-2.0.txt)
// Retrieved  : {retrieved}
// Dataset    : SHA-256 {dataset_sha256}
// Contents   : {drivers} drivers ({vulnerable} "vulnerable driver", {malicious} "malicious");
//              {samples} samples carry an Authentihash, {unique} unique digests ({no_hash} samples had none and are left out)
//
// Each digest is the "Authentihash" LOLDrivers records for a sample: what Code Integrity computes over the
// file without its CheckSum field, certificate-table entry and certificate blob (see pe_authenticode.c), so it
// is the same for a renamed or re-signed copy.  g_KgVulnClass has one character per digest: '1' when the
// sample is in LOLDrivers' "malicious" category, '0' for "vulnerable driver" (a digest in both is '1').
//
// Sorted ascending, so the driver can binary-search it once parsed.  Included by driver_load_guard.c only.
#pragma once

#define KG_VULN_HASH_COUNT {unique}

"""


def load_dataset(path, url):
    if path:
        raw = pathlib.Path(path).read_bytes()
    else:
        req = urllib.request.Request(url, headers={'User-Agent': 'kernelguard-import-loldrivers'})
        with urllib.request.urlopen(req, timeout=180) as r:
            raw = r.read()
    try:
        data = json.loads(raw)
    except ValueError as exc:
        sys.exit('import_loldrivers: the dataset is not JSON: %s' % exc)
    if not isinstance(data, list) or not data:
        sys.exit('import_loldrivers: unexpected dataset shape (expected a non-empty list of drivers)')
    return raw, data


def build_table(entries):
    """({digest: '0' or '1'}, statistics)."""
    table = {}
    stats = {'drivers': len(entries), 'vulnerable': 0, 'malicious': 0, 'samples': 0, 'no_hash': 0, 'other': set()}
    for e in entries:
        category = (e.get('Category') or '').strip().lower()
        if category == 'malicious':
            stats['malicious'] += 1
            klass = '1'
        else:
            stats['vulnerable'] += 1
            klass = '0'
            if category != 'vulnerable driver':
                stats['other'].add(category or '(none)')
        for sample in e.get('KnownVulnerableSamples') or []:
            auth = sample.get('Authentihash') or {}
            digest = (auth.get('SHA256') or '').strip().lower()
            if not HEX64.match(digest):
                stats['no_hash'] += 1
                continue
            stats['samples'] += 1
            table[digest] = '1' if (klass == '1' or table.get(digest) == '1') else '0'
    return table, stats


def render(table, stats, meta):
    digests = sorted(table)
    out = [HEADER.format(url=meta['url'], retrieved=meta['retrieved'], dataset_sha256=meta['sha256'],
                         drivers=stats['drivers'], vulnerable=stats['vulnerable'], malicious=stats['malicious'],
                         samples=stats['samples'], unique=len(digests), no_hash=stats['no_hash'])]
    out.append('static const char *const g_KgVulnHashHex[KG_VULN_HASH_COUNT] = {\n')
    out.extend('    "%s",\n' % d for d in digests)
    out.append('};\n\n')
    klass = ''.join(table[d] for d in digests)
    out.append('static const char g_KgVulnClass[KG_VULN_HASH_COUNT + 1] =\n')
    for i in range(0, len(klass), 64):
        out.append('    "%s"%s\n' % (klass[i:i + 64], ';' if i + 64 >= len(klass) else ''))
    if not klass:
        out.append('    "";\n')
    return ''.join(out)


def parse_existing(text):
    """{digest: class} from a header this tool wrote."""
    digests = re.findall(r'^    "([0-9a-f]{64})",$', text, re.M)
    body = text.rsplit('g_KgVulnClass', 1)[-1]
    klass = ''.join(re.findall(r'^    "([01]*)"', body, re.M))
    if len(klass) != len(digests):
        raise ValueError('the class string (%d) and the digest list (%d) differ in length' % (len(klass), len(digests)))
    return dict(zip(digests, klass))


def main():
    ap = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    ap.add_argument('--input', help='a saved drivers.json instead of downloading')
    ap.add_argument('--url', default=URL)
    ap.add_argument('--output', type=pathlib.Path, default=OUTPUT)
    ap.add_argument('--retrieved', default=datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%d'))
    ap.add_argument('--check', action='store_true', help='report whether the header is up to date; write nothing')
    a = ap.parse_args()

    raw, entries = load_dataset(a.input, a.url)
    table, stats = build_table(entries)
    if not table:
        sys.exit('import_loldrivers: no Authentihash SHA-256 found in the dataset; the format may have changed')
    if stats['other']:
        print('note: categories other than "vulnerable driver" and "malicious" were treated as vulnerable: %s'
              % ', '.join(sorted(stats['other'])), file=sys.stderr)

    if a.check:
        try:
            have = parse_existing(a.output.read_text())
        except (OSError, ValueError) as exc:
            print('import_loldrivers: cannot read %s: %s' % (a.output, exc), file=sys.stderr)
            return 1
        added = sorted(set(table) - set(have))
        removed = sorted(set(have) - set(table))
        reclassed = sorted(d for d in set(table) & set(have) if table[d] != have[d])
        if not (added or removed or reclassed):
            print('%s is up to date: %d digests' % (a.output.name, len(table)))
            return 0
        print('%s is out of date: %d added, %d removed, %d changed class (dataset now has %d digests, header has %d)'
              % (a.output.name, len(added), len(removed), len(reclassed), len(table), len(have)))
        return 1

    meta = {'url': a.url if not a.input else URL, 'retrieved': a.retrieved,
            'sha256': hashlib.sha256(raw).hexdigest()}
    a.output.write_text(render(table, stats, meta))
    print('wrote %s: %d digests from %d drivers (%d vulnerable driver, %d malicious); %d samples had no Authentihash'
          % (a.output.relative_to(ROOT) if a.output.is_relative_to(ROOT) else a.output, len(table),
             stats['drivers'], stats['vulnerable'], stats['malicious'], stats['no_hash']))
    return 0


if __name__ == '__main__':
    sys.exit(main())
