#!/usr/bin/env python3
"""
wdk_syntax_check.py - type-check the Windows sources on Linux, against the real Windows headers.

The driver (windows/src) and the monitor (windows/usermode) cannot be built here: that needs MSVC and
MSBuild. What can be checked is that every source parses and type-checks against the Windows 11 WDK/SDK
headers. This tool fetches just those headers from the Microsoft NuGet packages (HTTP range requests,
about 180 MB instead of 1 GB), and runs `clang -fsyntax-only` in Microsoft-compatible mode.

It is a compile check only: nothing is linked, MSVC-specific behaviour is not reproduced, and nothing
runs. A pass means "this compiles against these headers with clang", not "this works on Windows".

  tools/wdk_syntax_check.py                  check driver and monitor (headers cached in .wdk-cache/)
  tools/wdk_syntax_check.py --driver         only windows/src/*.c
  tools/wdk_syntax_check.py --files a.c b.c  only these files (driver or monitor, decided by directory)
  tools/wdk_syntax_check.py --cache DIR      keep the downloaded headers elsewhere
  tools/wdk_syntax_check.py -v               show clang's warnings too

Needs: clang (>= 15), and the Python package `remotezip` (pip install remotezip).
Exit status: 0 all files compile, 1 an error, 2 the environment is not usable.
"""
import argparse
import os
import pathlib
import re
import shutil
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent

KIT = '10.0.26100.0'
WDK_URL = ('https://api.nuget.org/v3-flatcontainer/microsoft.windows.wdk.x64/10.0.26100.6584/'
           'microsoft.windows.wdk.x64.10.0.26100.6584.nupkg')
SDK_URL = ('https://api.nuget.org/v3-flatcontainer/microsoft.windows.sdk.cpp/10.0.26100.9169/'
           'microsoft.windows.sdk.cpp.10.0.26100.9169.nupkg')

# (package, subtree prefixes to extract)
FETCH = [
    ('wdk', WDK_URL, [f'c/Include/{KIT}/km/']),
    ('sdk', SDK_URL, [f'c/Include/{KIT}/shared/', f'c/Include/{KIT}/um/']),
]

# The MSVC intrinsics that are neither clang builtins nor declared by the WDK headers.
INTRIN_STUB = """\
/* stand-in for MSVC <intrin.h> (generated by tools/wdk_syntax_check.py) */
#pragma once
#include <emmintrin.h>
unsigned __int64 __readmsr(unsigned long);
void __writemsr(unsigned long, unsigned __int64);
unsigned __int64 __readcr4(void);
void __writecr4(unsigned __int64);
void __sidt(void *);
"""

COMMON = ['--target=x86_64-pc-windows-msvc', '-fsyntax-only', '-x', 'c', '-std=gnu11', '-fms-extensions',
          '-fms-compatibility', '-fms-compatibility-version=19.40',
          '-Wno-microsoft', '-Wno-ignored-attributes', '-Wno-pragma-pack', '-Wno-unknown-pragmas',
          '-Wno-ignored-pragma-intrinsic', '-Wno-nonportable-include-path', '-Wno-int-to-void-pointer-cast',
          '-Wno-deprecated-declarations', '-Wno-visibility',
          '-D_AMD64_', '-DAMD64', '-D_WIN64', '-DNTDDI_VERSION=0x0A000009', '-DWINVER=0x0A00',
          '-D_WIN32_WINNT=0x0A00']
DRIVER_DEFS = ['-DWINNT=1', '-D_KERNEL_MODE=1', '-DPOOL_NX_OPTIN=1', '-DNT_UP=0', '-DNTSTRSAFE_LIB',
               '-DDBG=1', '-D_DEBUG']
USER_DEFS = ['-D_CRT_SECURE_NO_WARNINGS']


def fetch(cache):
    try:
        from remotezip import RemoteZip
    except ImportError:
        sys.exit('wdk_syntax_check: the Python package "remotezip" is missing (pip install remotezip)')
    for name, url, prefixes in FETCH:
        marker = cache / f'.{name}-{KIT}.done'
        if marker.exists():
            continue
        print(f'fetching {name} headers ({", ".join(p.rsplit("/", 2)[-2] for p in prefixes)}) ...', flush=True)
        with RemoteZip(url) as z:
            names = [i.filename for i in z.infolist()
                     if not i.filename.endswith('/') and any(i.filename.startswith(p) for p in prefixes)]
            for n in names:
                z.extract(n, cache / name)
        marker.write_text('ok\n')


class CaseFolder:
    """
    The Windows headers are included with whatever capitalisation the includer likes ("Windows.h",
    "DriverSpecs.h"); Windows does not care and Linux does. Every header found by a case-insensitive
    match is exposed through a symlink in `overlay`, created the first time clang asks for it.
    """

    def __init__(self, roots, overlay):
        self.overlay = overlay
        self.index = {}
        for base in roots:
            for dirpath, _, files in os.walk(base):
                for f in files:
                    full = pathlib.Path(dirpath) / f
                    self.index.setdefault(str(full.relative_to(base)).lower(), full)

    def add(self, missing):
        found = self.index.get(missing.replace('\\', '/').lower())
        if not found:
            return False
        link = self.overlay / missing.replace('\\', '/')
        link.parent.mkdir(parents=True, exist_ok=True)
        if not link.exists() and not link.is_symlink():
            link.symlink_to(found)
        return True


def check(clang, args, cf, verbose):
    for _ in range(600):
        r = subprocess.run([clang] + args, capture_output=True, text=True)
        missing = re.findall(r"fatal error: '([^']+)' file not found", r.stderr)
        if missing and cf.add(missing[0]):
            continue
        return r
    raise RuntimeError('header resolution did not converge')


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--cache', type=pathlib.Path, default=ROOT / '.wdk-cache')
    ap.add_argument('--driver', action='store_true', help='only windows/src')
    ap.add_argument('--monitor', action='store_true', help='only windows/usermode')
    ap.add_argument('--files', nargs='+', type=pathlib.Path)
    ap.add_argument('--clang', default=os.environ.get('CLANG') or shutil.which('clang'))
    ap.add_argument('-v', '--verbose', action='store_true')
    a = ap.parse_args()

    if not a.clang:
        print('wdk_syntax_check: clang not found (set CLANG or install clang)', file=sys.stderr)
        return 2
    a.cache.mkdir(parents=True, exist_ok=True)
    fetch(a.cache)

    km = a.cache / 'wdk' / 'c' / 'Include' / KIT / 'km'
    shared = a.cache / 'sdk' / 'c' / 'Include' / KIT / 'shared'
    um = a.cache / 'sdk' / 'c' / 'Include' / KIT / 'um'
    stub = a.cache / 'stub'
    overlay = a.cache / 'overlay'
    stub.mkdir(exist_ok=True)
    (stub / 'intrin.h').write_text(INTRIN_STUB)
    if overlay.exists():
        shutil.rmtree(overlay)
    overlay.mkdir()

    src = ROOT / 'windows' / 'src'
    usr = ROOT / 'windows' / 'usermode'
    if a.files:
        files = [(f.resolve()) for f in a.files]
    else:
        files = []
        if not a.monitor:
            files += sorted(src.glob('*.c'))
        if not a.driver:
            files += sorted(usr.glob('*.c'))

    cf = CaseFolder([km, shared, um, km / 'crt', src, usr], overlay)
    rc = 0
    for f in files:
        driver = src in f.parents
        inc = [f'-I{overlay}', f'-I{stub}'] if driver else [f'-I{overlay}']
        if driver:
            inc += [f'-I{km}', f'-I{shared}', f'-idirafter{km / "crt"}', f'-I{src}']
            args = COMMON + DRIVER_DEFS + inc + [str(f)]
        else:
            # The user-mode headers do not need the CRT; <wchar.h> comes from the WDK's crt directory.
            inc += [f'-I{um}', f'-I{shared}', f'-idirafter{km / "crt"}', f'-I{usr}']
            args = COMMON + USER_DEFS + inc + [str(f)]
        r = check(a.clang, args, cf, a.verbose)
        rel = f.relative_to(ROOT)
        errors = [l for l in r.stderr.splitlines() if ': error:' in l or ': fatal error:' in l]
        if r.returncode or errors:
            rc = 1
            print(f'FAIL  {rel}')
            print('\n'.join('      ' + l for l in (errors or r.stderr.splitlines()[-10:])[:12]))
        else:
            warns = sum(1 for l in r.stderr.splitlines() if ': warning:' in l and str(ROOT) in l)
            print(f'ok    {rel}' + (f'   ({warns} warning(s) in our code)' if warns else ''))
            if a.verbose and r.stderr:
                print(r.stderr)
    return rc


if __name__ == '__main__':
    sys.exit(main())
